Galaxy/config/routes.rb
Galaxy::Application.routes.draw do
  resources :projects do
    resources :supported_environments, :controller => 'product_supported_environments', only: :index
    get :test_result_of_latest_task, :on => :member
    get :test_result_passrate_trend, :on => :member
  end

  resources :providers
  
  resources :subscribers

  resources :diagnostic_logs

  resources :rankings

  resources :releases

  resources :branches

  resources :automation_jobs do
    get :test_case_executions, :on => :member
  end

  get "task_results/:ids", to: "task_results#index"
  
  get "task_results/", to: "task_results#index", as: "task_results"
  
  resources :test_results

  resources :test_case_executions do 
    get :test_result, :on => :member
  end

  get "dashboard/index"
  
  get "help/index"
  
  resources :product_supported_environment_maps

  resources :supported_environments

  resources :automation_tasks do
    get :test_executions, :on => :member
    get :execution_progress, :on => :member
    get :automation_jobs, :on => :member
    get :rerun, :on => :member
    get :report, :on => :member
    put :cancel, :on => :member
  end

  controller :test_depot do
    get 'test_depot/index' => :index
    get 'test_depot/user_created_test_suites_index' => :user_created_test_suites_index
    get 'test_depot/test_suites_of_external_providers_index' => :test_suites_of_external_providers_index
    get 'test_depot/test_plans_of_external_providers_index' => :test_plans_of_external_providers_index
    post 'test_depot/testcases/refresh' => :refreshtestcases
    post 'test_depot/testsuites/refresh' => :refreshtestsuites
  end
  
  
  resources :test_suites
  
  resources :test_suites do
    get :sub_test_suites, :on => :member
    get :sub_test_cases, :on => :member
    get :sub_test_suites_and_cases, :on => :member
  end
  
  resources :test_cases

  resources :test_environments  

  resources :users do
    get :subscribed_projects, :on => :member
  end  
  
  resources :builds
  
  resources :products do
    resources :builds, :controller => 'product_builds', only: :index    
    get :branches, :on => :member
    get :releases, :on => :member
  end
  
  controller :login do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  root 'dashboard#index'

end

Galaxy/app/models/provider.rb
class Provider < ActiveRecord::Base
  private
  def Provider.initialize_from_json_params(params)
    provider = Provider.new    
    provider.id = params['ProviderId']
    provider.name = params['Name']
    provider.category = params['Category']
    provider.type = params['Type']
    provider.path = params['Path']
    provider.config = params['Config']
    provider.description = params['Description']
    provider.is_active = params['IsActive']
    provider
  end
  def Provider.get_provider_list_by_category(category) 
    list = Array.new 
    response = force_server["Providers?searchBy=category&category=#{category}"].get    
    if response!=''
      params = JSON.parse(response.body)
      params.each do |param|
        list.push Provider.initialize_from_json_params(param)
      end
    end
    list
  end

end

Galaxy/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render action: 'show', status: :created, location: @provider }
      else
        format.html { render action: 'new' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :category, :type, :path, :config, :string, :description, :is_active, :integer)
    end
end

Galaxy/app/helpers/providers_helper.rb
module ProvidersHelper
end

Galaxy/app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.number_field :category %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :config %><br>
    <%= f.text_field :config %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.text_field :is_active %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Galaxy/app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

Galaxy/app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Type</th>
      <th>Path</th>
      <th>Config</th>
      <th>String</th>
      <th>Description</th>
      <th>Is active</th>
      <th>Integer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.name %></td>
        <td><%= provider.category %></td>
        <td><%= provider.type %></td>
        <td><%= provider.path %></td>
        <td><%= provider.config %></td>
        <td><%= provider.string %></td>
        <td><%= provider.description %></td>
        <td><%= provider.is_active %></td>
        <td><%= provider.integer %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

Galaxy/app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

Galaxy/app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @provider.category %>
</p>

<p>
  <strong>Type:</strong>
  <%= @provider.type %>
</p>

<p>
  <strong>Path:</strong>
  <%= @provider.path %>
</p>

<p>
  <strong>Config:</strong>
  <%= @provider.config %>
</p>

<p>
  <strong>String:</strong>
  <%= @provider.string %>
</p>

<p>
  <strong>Description:</strong>
  <%= @provider.description %>
</p>

<p>
  <strong>Is active:</strong>
  <%= @provider.is_active %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @provider.integer %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>