Galaxy/config/routes.rb
Galaxy::Application.routes.draw do
  resources :projects do
    resources :supported_environments, :controller => 'product_supported_environments', only: :index
    get :test_result_of_latest_task, :on => :member
    get :test_result_passrate_trend, :on => :member
  end

  resources :providers
  
  resources :subscribers

  resources :diagnostic_logs

  resources :rankings

  resources :releases

  resources :branches

  resources :automation_jobs do
    get :test_case_executions, :on => :member
  end

  get "task_results/:ids", to: "task_results#index"
  
  get "task_results/", to: "task_results#index", as: "task_results"
  
  resources :test_results

  resources :test_case_executions do 
    get :test_result, :on => :member
  end

  get "dashboard/index"
  
  get "help/index"
  
  resources :product_supported_environment_maps

  resources :supported_environments

  resources :automation_tasks do
    get :test_executions, :on => :member
    get :execution_progress, :on => :member
    get :automation_jobs, :on => :member
    get :rerun, :on => :member
    get :report, :on => :member
    put :cancel, :on => :member
  end

  controller :test_depot do
    get 'test_depot/index' => :index
    get 'test_depot/user_created_test_suites_index' => :user_created_test_suites_index
    get 'test_depot/test_suites_of_external_providers_index' => :test_suites_of_external_providers_index
    get 'test_depot/test_plans_of_external_providers_index' => :test_plans_of_external_providers_index
    post 'test_depot/testcases/refresh' => :refreshtestcases
    post 'test_depot/testsuites/refresh' => :refreshtestsuites
  end
  
  
  resources :test_suites
  
  resources :test_suites do
    get :sub_test_suites, :on => :member
    get :sub_test_cases, :on => :member
    get :sub_test_suites_and_cases, :on => :member
  end
  
  resources :test_cases

  resources :test_environments  

  resources :users do
    get :subscribed_projects, :on => :member
  end  
  
  resources :builds
  
  resources :products do
    resources :builds, :controller => 'product_builds', only: :index    
    get :branches, :on => :member
    get :releases, :on => :member
  end
  
  controller :login do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  root 'dashboard#index'

end

Galaxy/app/models/test_case_execution.rb
require 'date'
class TestCaseExecution < ActiveRecord::Base
  EXECUTION_STATUS =['NotRunning','Running','Completed','Failed']
  
  private
  
  def TestCaseExecution.get_force_build_by_execution_id(id)
    response = force_server['results/executions/' + id.to_s + '/build'].get
    if response!=''
      Build.initialize_from_json_params(JSON.parse(response.body))
    else
      nil
    end
  end
  
  def TestCaseExecution.get_force_test_execution_by_id(id)
    response = force_server['results/executions/' + id.to_s].get
    TestCaseExecution.initialize_from_json_params(JSON.parse(response.body))
  end
  
  def TestCaseExecution.get_all_force_test_executions()
    list = Array.new    
    response = force_server['results/executions'].get
    if response!=''
      params = JSON.parse(response.body)
      params.each do |param|
        p param
        list.push TestCaseExecution.initialize_from_json_params(param)      
      end
    end
    list
  end
  
  def TestCaseExecution.create_force_test_execution(params)
    response = force_server['results/executions'].post TestCaseExecution.serialize_params_to_json(params),:content_type => 'application/json'
    TestCaseExecution.initialize_from_json_params(JSON.parse(response.body))
  end
  
  def TestCaseExecution.update_force_test_execution(id, params)
    response = force_server['results/executions/' + id.to_s].put TestCaseExecution.serialize_params_to_json(params),:content_type => 'application/json'
    TestCaseExecution.initialize_from_json_params(JSON.parse(response.body))
  end
  
  def TestCaseExecution.delete_force_test_execution(id)
    response = force_server['results/executions/' + id.to_s].delete
  end
  
  def TestCaseExecution.initialize_from_json_params(params)
    test_execution = TestCaseExecution.new
    test_execution.id = params['ExecutionId']
    test_execution.test_case_id = params['TestCaseId']
    test_execution.job_id = params['JobId']
    test_execution.status = params['Status']
    test_execution.info = params['Info']
    begin
      test_execution.start_time = Time.parse(db_time_to_rails_time(params['StartTime']))
    rescue
      test_execution.start_time = nil
    end
    begin
      test_execution.end_time = Time.parse(db_time_to_rails_time(params['EndTime']))
    rescue
      test_execution.end_time = nil
    end  
    test_execution.retry_times = params['RetryTimes']
    test_execution

  end
  
  def TestCaseExecution.serialize_params_to_json(params)
    hash = Hash.new
    hash[:TestCaseId] = params['test_case_id']
    hash[:JobId] = params['job_id']
    hash[:Status] = params['status']
    hash[:StartTime] = params['start_time']
    hash[:EndTime] = params['end_time']
    hash[:RetryTimes] = params['retry_times']
    hash[:Info] = params['info']
    JSON.generate(hash)
  end
end

Galaxy/app/controllers/test_case_executions_controller.rb
class TestCaseExecutionsController < ApplicationController
  before_action :set_test_case_execution, only: [:show, :edit, :update, :destroy]

  # GET /test_case_executions
  # GET /test_case_executions.json
  def index
    @test_case_executions = TestCaseExecution.get_all_force_test_executions
  end

  # GET /test_case_executions/1
  # GET /test_case_executions/1.json
  def show
  end

  # GET /test_case_executions/new
  def new
    @test_case_execution = TestCaseExecution.new
  end

  # GET /test_case_executions/1/edit
  def edit
    def @test_case_execution.new_record?()
      false
    end
  end

  # POST /test_case_executions
  # POST /test_case_executions.json
  def create
    @test_case_execution = TestCaseExecution.create_force_test_execution(test_case_execution_params)

    respond_to do |format|
      if @test_case_execution
        format.html { redirect_to test_case_execution_path(@test_case_execution), notice: 'Test case execution was successfully created.' }
        format.json { render action: 'show', status: :created, location: @test_case_execution }
      else
        format.html { render action: 'new' }
        format.json { render json: @test_case_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_case_executions/1
  # PATCH/PUT /test_case_executions/1.json
  def update
    @test_case_execution = TestCaseExecution.update_force_test_execution(params[:id],test_case_execution_params)
    respond_to do |format|
      if @test_case_execution
        format.html { redirect_to test_case_execution_path(@test_case_execution), notice: 'Test case execution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @test_case_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_case_executions/1
  # DELETE /test_case_executions/1.json
  def destroy
    TestCaseExecution.delete_force_test_execution
    respond_to do |format|
      format.html { redirect_to test_case_executions_url }
      format.json { head :no_content }
    end
  end

  def test_result
     @test_result = TestResult.get_force_test_result_by_execution_id(params[:id])
     @historical_results = TestResult.get_force_historical_test_results_by_testcase_id(TestCaseExecution.get_force_test_execution_by_id(params[:id]).test_case_id)
     respond_to do |format|
       format.html { render :partial=>'test_results/show_one_result'}
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_case_execution
      @test_case_execution = TestCaseExecution.get_force_test_execution_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_case_execution_params
      params.require(:test_case_execution).permit(:test_case_id, :job_id, :status, :start_time, :end_time, :retry_times)
    end
end

Galaxy/app/helpers/test_case_executions_helper.rb
module TestCaseExecutionsHelper
  def force_jobs_list
    
  end
  
  def execution_status_list
    TestCaseExecution::EXECUTION_STATUS.collect{|s|[s,TestCaseExecution::EXECUTION_STATUS.index(s)]}
  end
  
  def execution_status_name(id)
    TestCaseExecution::EXECUTION_STATUS[id]
  end
end

Galaxy/app/views/test_case_executions/_form.html.erb
<%= form_for(@test_case_execution) do |f| %>
  <% if @test_case_execution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_case_execution.errors.count, "error") %> prohibited this test_case_execution from being saved:</h2>

      <ul>
      <% @test_case_execution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :test_case_id %><br>
    <%= f.select :test_case_id,force_test_cases_list %>
  </div>
  <div class="field">
    <%= f.label :job_id %><br>
    <%= f.number_field :job_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, execution_status_list %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :retry_times %><br>
    <%= f.number_field :retry_times %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Galaxy/app/views/test_case_executions/_test_case_executions_list.html.erb
<table>
  <thead>
    <tr>
      <th>Test case</th>
      <th>Job</th>
      <th>Status</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Retry times</th>
      <th>Operations</th>
    </tr>
  </thead>

  <tbody>
    <% @test_case_executions.each do |test_case_execution| %>
      <tr>
        <td><%= force_test_case_name(test_case_execution.test_case_id) %></td>
        <td><%= test_case_execution.job_id %></td>
        <td><%= execution_status_name(test_case_execution.status) %></td>
        <td><span class="date_time"><%= test_case_execution.start_time %></span></td>
        <td><span class="date_time"><%= test_case_execution.end_time %></span></td>
        <td><%= test_case_execution.retry_times %></td>
        <td class="item_operations"><%= link_to 'Show', test_case_execution %>
        <%= link_to 'Edit', edit_test_case_execution_path(test_case_execution) %>
        <%= link_to 'Destroy', test_case_execution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Galaxy/app/views/test_case_executions/_test_case_executions_list_internal_for_task.html.erb
<table id='task_executions_table'>
  <thead>
    <tr>
      <th>Test case</th>
      <th>Job</th>
      <th>Status</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Result</th>
    </tr>
  </thead>

  <tbody>
    <% @test_case_executions.each do |test_case_execution| %>
      <% result = force_test_result_of_test_execution(test_case_execution)%>
      <tr>      	
        <td title="<%= force_test_case_name(test_case_execution.test_case_id) %>"><%= truncate(force_test_case_name(test_case_execution.test_case_id), :length=>100) %></td>
        <td><%= test_case_execution.job_id %></td>
        <td><%= execution_status_name(test_case_execution.status) %></td>
        <td><span class="date_time"><%= test_case_execution.start_time %></span></td>
        <td><span class="date_time"><%= test_case_execution.end_time %></span></td>
        <td><a class='force_task_execution_result_link <%= display_class_for_result(result)%>' href="<%= test_result_test_case_execution_path(test_case_execution) %>"><%= result%></a></td>        
      </tr>
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
	$(".force_task_execution_result_link").on('click',function(e){
		$("#automation_task_execution_result_tab_link").attr("href",$(this).attr("href"));//change the link for the result tab to the result of the clicked execution
	    $("#task_execution_details_tabs").tabs('option','active',3);//active the results tab for this execution
	    e.preventDefault(); 
    });
    $("#task_executions_table").dataTable({
		"bJQueryUI": true,
        "sPaginationType": "full_numbers",
        "bAutoWidth": false,
        "bFilter": true,
        "bSort": true,
        "bInfo": false,
        "bPaginate": false
	});
	$(".force_task_execution_result_link").button();
	
	$("span.date_time").each(function(){
		var utc = $(this).html().replace(/-/g, "/");
		if(utc!='')
		{
			var d = new Date(utc);
			//var year = d.getFullYear();
			//var month = d.getMonth() + 1;
			//var day = d.getDate();
			//var hour = d.getHours();
			//var minute = d.getMinutes();
			//var second = d.getSeconds();
			//$(this).html(year + '-' + month + '-' + day + ' ' + hour + ':' + minute + ':' + second);
			$(this).html(d.toLocaleString());
		}
		else
		{
			
		}
	});
</script>

Galaxy/app/views/test_case_executions/edit.html.erb
<h1>Editing test_case_execution</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_case_execution %> |
<%= link_to 'Back', test_case_executions_path %>

Galaxy/app/views/test_case_executions/index.html.erb
<fieldset>
	<legend class="galaxy_legend">Listing Test Case Executions</legend>
	<%= render 'test_case_executions_list' %>
</fieldset>


<%= link_to 'New Test case execution', new_test_case_execution_path %>
<%= render :partial => 'layouts/index_table_style_javascript'%>

Galaxy/app/views/test_case_executions/new.html.erb
<h1>New test_case_execution</h1>

<%= render 'form' %>

<%= link_to 'Back', test_case_executions_path %>

Galaxy/app/views/test_case_executions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Test case:</strong>
  <%= @test_case_execution.test_case_id %>
</p>

<p>
  <strong>Job:</strong>
  <%= @test_case_execution.job_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @test_case_execution.status %>
</p>

<p>
  <strong>Start time:</strong>
  <span class="date_time"><%= @test_case_execution.start_time %></span>
</p>

<p>
  <strong>End time:</strong>
  <span class="date_time"><%= @test_case_execution.end_time %></span>
</p>

<p>
  <strong>Retry times:</strong>
  <%= @test_case_execution.retry_times %>
</p>

<%= link_to 'Edit', edit_test_case_execution_path(@test_case_execution) %> |
<%= link_to 'Back', test_case_executions_path %>