Galaxy/config/routes.rb
Galaxy::Application.routes.draw do
  resources :projects do
    resources :supported_environments, :controller => 'product_supported_environments', only: :index
    get :test_result_of_latest_task, :on => :member
    get :test_result_passrate_trend, :on => :member
  end

  resources :providers
  
  resources :subscribers

  resources :diagnostic_logs

  resources :rankings

  resources :releases

  resources :branches

  resources :automation_jobs do
    get :test_case_executions, :on => :member
  end

  get "task_results/:ids", to: "task_results#index"
  
  get "task_results/", to: "task_results#index", as: "task_results"
  
  resources :test_results

  resources :test_case_executions do 
    get :test_result, :on => :member
  end

  get "dashboard/index"
  
  get "help/index"
  
  resources :product_supported_environment_maps

  resources :supported_environments

  resources :automation_tasks do
    get :test_executions, :on => :member
    get :execution_progress, :on => :member
    get :automation_jobs, :on => :member
    get :rerun, :on => :member
    get :report, :on => :member
    put :cancel, :on => :member
  end

  controller :test_depot do
    get 'test_depot/index' => :index
    get 'test_depot/user_created_test_suites_index' => :user_created_test_suites_index
    get 'test_depot/test_suites_of_external_providers_index' => :test_suites_of_external_providers_index
    get 'test_depot/test_plans_of_external_providers_index' => :test_plans_of_external_providers_index
    post 'test_depot/testcases/refresh' => :refreshtestcases
    post 'test_depot/testsuites/refresh' => :refreshtestsuites
  end
  
  
  resources :test_suites
  
  resources :test_suites do
    get :sub_test_suites, :on => :member
    get :sub_test_cases, :on => :member
    get :sub_test_suites_and_cases, :on => :member
  end
  
  resources :test_cases

  resources :test_environments  

  resources :users do
    get :subscribed_projects, :on => :member
  end  
  
  resources :builds
  
  resources :products do
    resources :builds, :controller => 'product_builds', only: :index    
    get :branches, :on => :member
    get :releases, :on => :member
  end
  
  controller :login do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  root 'dashboard#index'

end

Galaxy/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessor :vcs_server 
  attr_accessor :vcs_server_type
  attr_accessor :vcs_server_password
  attr_accessor :vcs_server_username
  attr_accessor :vcs_server_root_path
  attr_accessor :run_time
  VCSSERVER_TYPES = [['TFS',1],['ClearCase',2],['Shared Folder',3],['Git',4],['Not Sync',5]]
  RUN_TIME_TYPES = [['CSharpNUnit',0],['RubyMiniTest',1]]
  private
  #handle the communication with the Force Server
  def Project.get_force_project_by_id(id)
    response = force_server['projects/' + id.to_s].get
    Project.initialize_from_json_params(JSON.parse(response.body))
  end
  
  def Project.get_all_force_projects()
    list = Array.new    
    response = force_server['projects'].get
    params = JSON.parse(response.body)
    params.each do |param|
      list.push Project.initialize_from_json_params(param)      
    end
    list
  end
  
  def Project.create_force_project(params)
   
    response = force_server['projects/'].post Project.serialize_params_to_json(params),:content_type => 'application/json', :accept => 'application/json'
    Project.initialize_from_json_params(JSON.parse(response.body))
  end
  
  def Project.test_result_of_latest_task(id)
    response = force_server['projects/' + id.to_s + '/latestresultsummary'].get
    AutomationTaskRunningStatus.initialize_from_json_params(JSON.parse(response.body))
  end
  
  def Project.test_result_passrate_trend(id)
    response = force_server['projects/' + id.to_s + '/passratehistory'].get
    AutomationTaskRunningStatus.initialize_from_json_params(JSON.parse(response.body))
  end
  
  def Project.update_force_project(id, params)
    response = force_server['projects/' + id.to_s].put Project.serialize_params_to_json(params),:content_type => 'application/json', :accept=>'application/json'
    Project.initialize_from_json_params(JSON.parse(response.body))
  end
  
  def Project.delete_force_project(id)
    response = force_server['projects/' + id.to_s].delete
  end
  
   def Project.get_force_supported_environments_for_project(id)
    list = Array.new 
    response = force_server['projects/' + id.to_s + '/supportedenvironments'].get
    if(response != '')
      params = JSON.parse(response.body)
      params.each do |param|
        list.push SupportedEnvironment.initialize_from_json_params(param)      
      end
      list      
    else
      nil
    end
   end

  def Project.initialize_from_json_params(params)
    project = Project.new
    project.id = params['ProjectId']
    project.vcs_server = params['VCSServer']
    project.vcs_server_type = params['VCSType']
    project.vcs_server_password = params['VCSPassword']
    project.vcs_server_username = params['VCSUser']
    project.vcs_server_root_path = params['VCSRootPath']
    project.run_time = params['RunTime']    
    project.name = params['Name']
    project.description = params['Description']
    project
  end
  
  def Project.serialize_params_to_json(params)
    hash = Hash.new
    hash[:Name] = params['name']    
    hash[:VCSRootPath] = params['vcs_server_root_path']
    #the project's runtime is decayed, we use the runtime of the test case instead
    hash[:RunTime] = 0 #RUN_TIME_TYPES[params['run_time'].to_i][0]
    hash[:VCSServer] = params['vcs_server'] 
    hash[:VCSUser] =  params['vcs_server_username'] 
    hash[:VCSType] = params['vcs_server_type'] 
    hash[:VCSPassword] = params['vcs_server_password']    
    hash[:Description] = params['description']
    JSON.generate(hash)
  end
end

Galaxy/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.get_all_force_projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    def @project.new_record?()
        false
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    respond_to do |format|
      if Project.create_force_project(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if Project.update_force_project(params[:id], project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    Project.delete_force_project(params[:id])
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
  
  def test_result_of_latest_task
    @result = Project.test_result_of_latest_task(params[:id])
  end
  
  def test_result_passrate_trend
    @result_trend = Project.test_result_passrate_trend(params[:id])
  end    
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.get_force_project_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :vcs_server , :vcs_server_type, :vcs_server_root_path,:vcs_server_username,:vcs_server_password, :run_time)
    end
end

Galaxy/app/helpers/projects_helper.rb
module ProjectsHelper
  def project_type_options_list (param)    
    param.collect{|t|[t[0], t[1]]}
  end
  def find_index_of_type_options(type_options,value)
    type_options.each{|t| 
      if t[0]==value 
        return t[1] 
        end
        }
  end  
  def find_name (list,id)
    list.each {|v|
      if v[1]==id
        return v[0]
      end
    }
  end
end

Galaxy/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size:30, :placeholder=>'Please enter the project name here.' %>
  </div>  
  <div class="field">
  	<%= f.label :vcs_server_type, 'VCS type' %><br>
  	<%= f.select :vcs_server_type, options_for_select(project_type_options_list(Project::VCSSERVER_TYPES),@project.vcs_server_type),:prompt => 'Select the VCS Server Type.' %>
  </div>
  <div class="field">
 	<%= f.label :vcs_server, 'VCS server'%><br>
    <%= f.text_field :vcs_server, :size=>30, :placeholder=>'Enter VCSServer Address.'%>
  </div>
  <div class="field">
 	<%= f.label :vcs_server_username, 'VCS server username'%><br>
    <%= f.text_field :vcs_server_username, :size=>25, :placeholder=>'Enter VCSServer username.'%>
  </div>
  <div class="field">
 	<%= f.label :vcs_server_password, 'VCS server password'%><br>
    <%= f.password_field :vcs_server_password, :size=>25, :placeholder=>'Enter VCSServer password.'%>
  </div>
  <div class="field">
 	<%= f.label :vcs_server_root_path, 'VCS server root path'%><br>
    <%= f.text_field :vcs_server_root_path, :size=>30, :placeholder=>'Enter VCSServer root path.'%>
  </div>
  <div class="field hide">
 	<%= f.label :run_time%><br>
    <%= f.select :run_time,options_for_select(project_type_options_list(Project::RUN_TIME_TYPES),find_index_of_type_options(Project::RUN_TIME_TYPES,@project.run_time)), :prompt=>'Select the run time type.'%>
  </div>
  <div class="field">  
    <%= f.label :description %><br>
    <%= f.text_area :description, :placeholder=>'please add the description here.', rows:5, cols:40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Galaxy/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

Galaxy/app/views/projects/index.html.erb
<fieldset>
	<legend class="galaxy_legend">Projects</legend>

	<table>
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Description</th>
	      <th>Subscribe</th>
	      <th>Operations</th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @projects.each do |project| %>
	      <tr>
	        <td><%= project.name %></td>
	        <td><%= project.description %></td>
	        <td align="center"> <%= check_box_tag "subscribe_check_box_#{project.id}", "check_box",-1!=find_subscriber_by_project_and_user_id(project,session[:user_id].to_s),:class=>'subscribe_check_box',:subscribe_id=>find_subscriber_by_project_and_user_id(project,session[:user_id].to_s),:user_id =>session[:user_id].to_s,:project_id =>project.id%></td>
	        <td class="item_operations">
	        	<%= link_to 'Show', project_path(project) %>
	        	<%= link_to 'Edit', edit_project_path(project) %>
	        	<% if @is_current_user_administrator %>
	        	<%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %>
	        	<% end %>
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</fieldset>
<br>

<%= link_to 'New Project', new_project_path %>
<%= render :partial => 'layouts/index_table_style_javascript'%>
<script type="text/javascript">
				$(".subscribe_check_box").change(function(){
					var object =$(this);
					if ($(this).attr("subscribe_id")=="-1"){
						var params = {'subscriber':{'project_id':$(this).attr("project_id"), 'user_id':$(this).attr("user_id"), 'create_time':getLocalDateStringOfCurrent(),'subscriber_type':'1','description':''}};
						
						$.post("/subscribers",params,function(data){
							alert ("Subscribe Successfully!");
							object.attr("subscribe_id",data.id);		
						},'json');
					}
					else {
						suburl = '/subscribers/'+$(this).attr("subscribe_id");
						subid = $(this).attr("subscribe_id");
						$.ajax({
							id: subid,
							type:"DELETE",
							url:suburl,
							dataType:"json",
							success:function(){
								object.attr("subscribe_id","-1");
								alert ("Unsubscribe Successfully!");
							}
						});
						
					}					
				});
</script>

Galaxy/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

Galaxy/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>
<p>
	<strong>VCS server type: </strong>
		<%= find_name(Project::VCSSERVER_TYPES,@project.vcs_server_type)%>
</p>
<p>
	<strong>VCS server: </strong>
	<%= @project.vcs_server%>
</p>
<p>
	<strong>VCS user name: </strong>
	<%= @project.vcs_server_username%>
</p>
<p>
	<strong>VCS root path: </strong>
	<%= @project.vcs_server_root_path%>
</p>
<!-- 
<p>
	<strong>Run time: </strong>
	<%= @project.run_time%>	
</p>	
-->		
<p>
  <strong>Description: </strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>