Galaxy/config/routes.rb
Galaxy::Application.routes.draw do
  resources :projects do
    resources :supported_environments, :controller => 'product_supported_environments', only: :index
    get :test_result_of_latest_task, :on => :member
    get :test_result_passrate_trend, :on => :member
  end

  resources :providers
  
  resources :subscribers

  resources :diagnostic_logs

  resources :rankings

  resources :releases

  resources :branches

  resources :automation_jobs do
    get :test_case_executions, :on => :member
  end

  get "task_results/:ids", to: "task_results#index"
  
  get "task_results/", to: "task_results#index", as: "task_results"
  
  resources :test_results

  resources :test_case_executions do 
    get :test_result, :on => :member
  end

  get "dashboard/index"
  
  get "help/index"
  
  resources :product_supported_environment_maps

  resources :supported_environments

  resources :automation_tasks do
    get :test_executions, :on => :member
    get :execution_progress, :on => :member
    get :automation_jobs, :on => :member
    get :rerun, :on => :member
    get :report, :on => :member
    put :cancel, :on => :member
  end

  controller :test_depot do
    get 'test_depot/index' => :index
    get 'test_depot/user_created_test_suites_index' => :user_created_test_suites_index
    get 'test_depot/test_suites_of_external_providers_index' => :test_suites_of_external_providers_index
    get 'test_depot/test_plans_of_external_providers_index' => :test_plans_of_external_providers_index
    post 'test_depot/testcases/refresh' => :refreshtestcases
    post 'test_depot/testsuites/refresh' => :refreshtestsuites
  end
  
  
  resources :test_suites
  
  resources :test_suites do
    get :sub_test_suites, :on => :member
    get :sub_test_cases, :on => :member
    get :sub_test_suites_and_cases, :on => :member
  end
  
  resources :test_cases

  resources :test_environments  

  resources :users do
    get :subscribed_projects, :on => :member
  end  
  
  resources :builds
  
  resources :products do
    resources :builds, :controller => 'product_builds', only: :index    
    get :branches, :on => :member
    get :releases, :on => :member
  end
  
  controller :login do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  root 'dashboard#index'

end

Galaxy/app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence=>true, :uniqueness=>true
  
  attr_accessor :email
  USER_TYPES = ['ATF','AD']
  USER_ROLES = ['SystemAdmin','User','Viewer']
  

  
  private
  
  #The logic to handle the communication with the Force service. 
  
  
  def User.get_force_user_by_id(user_id)    
    response = force_server['users/' + user_id.to_s].get
    if(response=='')
      nil
    else
      User.initiate_from_json_params(JSON.parse(response.body))
    end
  end 
  
  def User.get_all_force_users
    user_list = Array.new    
    response = force_server['users'].get
    params = JSON.parse(response.body)
    params.each do |param|
      user_list.push User.initiate_from_json_params(param)      
    end
    user_list
  end
  
  def User.create_force_user(params)      
    response = force_server['users/'].post User.serialize_params_to_json(params),:content_type => 'application/json'
    User.initiate_from_json_params(JSON.parse(response.body))
  end 
  
  
  def User.update_force_user(user_id,params) 
    response = force_server['users/' + user_id.to_s].put User.serialize_params_to_json(params),:content_type => 'application/json'
    User.initiate_from_json_params(JSON.parse(response.body))
  end
  
  def User.delete_force_user(user_id) 
    response = force_server['users/' + user_id.to_s].delete
  end  

  def User.get_subscribed_projects(user_id)
    subscribed_projects = Array.new
    response = force_server['users/' + user_id.to_s + '/subscribed_projects'].get
    params = JSON.parse(response.body)
    params.each do |param|
      subscribed_projects.push Project.initialize_from_json_params(param)
    end
    subscribed_projects
  end

  #help method
  
  def User.initiate_from_json_params(params)
    user = User.new
    user.id = params['UserId']
    user.email = params['Email']
    user.name = params['Username']
    user.password = params['Password']
    user.is_active = params['IsActive']
    user.description = params['Description']
    user.user_type = params['Type']
    user.role = params['Role']
    user
  end
  
  def User.serialize_params_to_json(params)
    hash = Hash.new
    hash[:Username] = params['name']
    hash[:Email] = params['email']
    hash[:Password] = params['password']
    hash[:IsActive] = params['is_active']
    hash[:Type] = params['user_type']
    hash[:Description] = params['description']
    hash[:Role] = params['role']
    JSON.generate(hash)
  end
  
  def User.authenticate(name, password)
    hash = {:Username => name, :Password=>password}   
    begin
      response = force_server['users/isUserValid'].post JSON.generate(hash),:content_type => 'application/json'
      if(response.body == '')
        return nil
      else
        return User.initiate_from_json_params(JSON.parse(response.body))
      end
    rescue => e
      #the login is failed for internal errors, here we may need to log the failure
      return nil
    end
  end
end

Galaxy/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #skip_before_filter :authorize
  # GET /users
  # GET /users.json
  def index
    @users = User.get_all_force_users
  end

  # GET /users/1
  # GET /users/1.json
  def show
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    #hack the rails
    def @user.new_record?()
        false
    end
  end

  # POST /users
  # POST /users.json
  def create
    #@user = User.new(user_params)    
    respond_to do |format|
      if User.create_force_user(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
      respond_to do |format|   
        if User.update_force_user(params[:id],user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.delete_force_user(params[:id])
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def subscribed_projects
    @subscribed_projects = User.get_subscribed_projects(params[:id])
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.get_force_user_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :user_type, :role, :is_active,:email, :description)      
    end
end

Galaxy/app/helpers/users_helper.rb
module UsersHelper
end

Galaxy/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :size => 40 %>
  </div>
  <div class="field hide">
    <%= f.label :password %><br>
    <%= f.password_field :password, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :size => 40 %>
  </div>
  <div class="field">
    <%= f.label :user_type %><br>
    <%= f.select :user_type, User::USER_TYPES.collect{|t| [t,User::USER_TYPES.index(t)]} %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.select :role, User::USER_ROLES.collect{|t|[t,User::USER_ROLES.index(t)]} %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br>
    <%= f.check_box :is_active, :checked_value => true, :unchecked_value => false %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 4, :cols => 40 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script type="text/javascript">
  if($("#user_user_type").val() == 1)
  {
    $("#user_password").parent().addClass("hide");
  }
  else
  {
    $("#user_password").parent().removeClass("hide");
  }
</script>

Galaxy/app/views/users/edit.html.erb
<h1>Editing user</h1>
<div class="galaxy_form">
	<fieldset>
		<legend>Please edit the user</legend>
		<%= render 'form' %>
	</fieldset>	
</div>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Galaxy/app/views/users/index.html.erb
<fieldset>
	<legend class="galaxy_legend">Users</legend>
	<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User type</th>
      <th>Role</th>
      <th>Is active</th>
      <th>Description</th>
      <th>Operations</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= force_user_type_name(user.user_type) %></td>
        <td><%= force_user_role_name(user.role) %></td>
        <td><%= user.is_active %></td>
        <td title='<%= user.description %>'><%= user.description[0..12] + '...' %></td>
        <td  class="item_operations">
          <%= link_to 'Show', user_path(user) %>
          <%= link_to 'Edit', edit_user_path(user) %>
          <% if @is_current_user_administrator %>
          <%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</fieldset>

<br>

<%= link_to 'New User', new_user_path %>
<%= render :partial => 'layouts/index_table_style_javascript'%>

Galaxy/app/views/users/new.html.erb
<h1>New user</h1>
<div class="galaxy_form">
	<fieldset>
		<legend>Please enter your detail</legend>
		<%= render 'form' %>
	</fieldset>	
</div>

<%= link_to 'Back', users_path %>

Galaxy/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>User type:</strong>
  <%= User::USER_TYPES[@user.user_type] %>
</p>

<p>
  <strong>Role:</strong>
  <%= User::USER_ROLES[@user.role] %>
</p>

<p>
  <strong>Is active:</strong>
  <%= (@user.is_active==1)?'True':'False' %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>